import Signaligner from '../pictures/projects/signaligner.png';
import Book from '../pictures/projects/book.png';
import Animator from '../pictures/projects/animator.png';
import Info from '../pictures/projects/info.png';
import Marble from '../pictures/projects/marble.png';
import Movie from '../pictures/projects/movie.png';
import Star from '../pictures/projects/star.png';
import Weeb from '../pictures/projects/weeb.png';
import Puzzle from '../pictures/projects/puzzle.png';

export const PROJECTS = [
  {
    key: 'signaligner',
    name: 'Signaligner',
    img: Signaligner,
    description: 'Worked with NEU mHealth Lab on a research project that uses accelerometer data to supoort activity recognition using Python and Javascript.',
    link: 'https://crowdgames.github.io/signaligner/',
  },
  {
    key: 'bookAyeAye',
    name: 'BookAyeAye',
    img: Book,
    description: 'An app built to detect where a book locates from a bookshelf using Android Studio and Google Vision API. It earns Google API Honorable Mention at BostonHacks 2019.',
    link: 'https://github.com/cindy1u0/BookAyeAye',
  },
  {
    key: 'weebsMeetNeets',
    name: 'Weebs Meet Neets',
    img: Weeb,
    description: 'A web app built to connect people who like anime together using React and Django.',
    link: 'https://github.com/cindy1u0/WeebsMeetNeets',
  },
  {
    key: 'star',
    name: 'Neighborhoods of Nearby Stars',
    img: Star,
    description: 'A program built to show nearby starts in space using Mathematica.',
    link: 'https://demonstrations.wolfram.com/NeighborhoodsOfNearbyStars/',
  },
  {
    key: 'topMovieSearch',
    name: 'Top Movie Search',
    img: Movie,
    description: 'A script built to scape top 10 moves from Rotten Tomatoes Weekend Box Office Chard using Shell.',
    link: 'https://github.com/cindy1u0/Top-Movie-Search',
  },
  {
    key: 'puzzle',  
    name: 'Polyominoes-puzzle-game',
    img: Puzzle,
    description: 'A game created to allow a user to drag the polyominoes to complete the puzzle (shaded area) that is being generated by the program using Java.',
    link: 'https://github.com/cindy1u0/Polyominoes-puzzle-game',
  },
  {
    key: 'infographics',
    name: 'Infographics',
    img: Info,
    description: 'A program built to show visualize large data using Mathematica.',
    link: 'https://community.wolfram.com/groups/-/m/t/1027435?p_p_auth=BOTd0UxD',
  },
  {
    key: '',
    name: 'Easy Animator',
    img: Animator,
    description: 'An animator built to convert motions in texts to an animation as well as allowing the user to edit the animation suing Java.',
    link: 'https://github.com/cindy1u0/Easy-Animator',
  },
  {
    key: 'solitaire',
    name: 'Marble Solitaire',
    img: Marble,
    description: 'A game created which simulates Peg Solitaire that has 3 board types, including English board, European board, and Triangular board using Java.',
    link: 'https://github.com/cindy1u0/Marble-Solitaire',
  },
]