import Signaligner from '../pictures/projects/signaligner.png';
import Book from '../pictures/projects/book.png';
import Animator from '../pictures/projects/animator.png';
import Info from '../pictures/projects/info.png';
import Marble from '../pictures/projects/marble.png';
import Movie from '../pictures/projects/movie.png';
import Star from '../pictures/projects/star.png';
import Weeb from '../pictures/projects/weeb.png';
import Puzzle from '../pictures/projects/puzzle.png';

export const PROJECTS = [
  {
    key: 'signaligner',
    name: 'Signaligner',
    img: Signaligner,
    description: 'I worked in a team of Sandbox members on a research project under the NEU mHealth Lab that uses accelerometer data to supoort activity recognition using Python and Javascript.',
    link: 'https://crowdgames.github.io/signaligner/',
  },
  {
    key: 'bookAyeAye',
    name: 'BookAyeAye',
    img: Book,
    description: 'I built an app with friends that finds where a book locates exactly on a bookshelf using Android Studio and Google Vision API. It earned Google API Honorable Mention at BostonHacks 2019.',
    link: 'https://github.com/cindy1u0/BookAyeAye',
  },
  {
    key: 'weebsMeetNeets',
    name: 'Weebs Meet Neets',
    img: Weeb,
    description: 'I built a web app with friends that connects people who like anime together using React and Django.',
    link: 'https://github.com/cindy1u0/WeebsMeetNeets',
  },
  {
    key: 'star',
    name: 'Neighborhoods of Nearby Stars',
    img: Star,
    description: 'I built a program that shows nearby stars in space using Mathematica.',
    link: 'https://demonstrations.wolfram.com/NeighborhoodsOfNearbyStars/',
  },
  {
    key: 'topMovieSearch',
    name: 'Top Movie Search',
    img: Movie,
    description: 'I wrote a script that scrapes top 10 movies from Rotten Tomatoes Weekend Box Office Chard using Shell.',
    link: 'https://github.com/cindy1u0/Top-Movie-Search',
  },
  {
    key: 'puzzle',  
    name: 'Polyominoes-puzzle-game',
    img: Puzzle,
    description: 'I co-created a game that allows a user to solve a puzzle with polynominoes that are generated by the program using Java.',
    link: 'https://github.com/cindy1u0/Polyominoes-puzzle-game',
  },
  {
    key: 'infographics',
    name: 'Infographics',
    img: Info,
    description: 'I built a program that visualizes large data using Mathematica.',
    link: 'https://community.wolfram.com/groups/-/m/t/1027435?p_p_auth=BOTd0UxD',
  },
  {
    key: '',
    name: 'Easy Animator',
    img: Animator,
    description: 'I co-created an animator that converts motions in texts to an animation as well as allowing a user to edit the animation using Java.',
    link: 'https://github.com/cindy1u0/Easy-Animator',
  },
  {
    key: 'solitaire',
    name: 'Marble Solitaire',
    img: Marble,
    description: 'I built a game which simulates Peg Solitaire with additional European board and Triangular board using Java.',
    link: 'https://github.com/cindy1u0/Marble-Solitaire',
  },
]